// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {assetserver} from '../models';
import {services} from '../models';
import {context} from '../models';
import {db} from '../models';
import {app} from '../models';

export function CancelExport(arg1:string):Promise<void>;

export function ClearSuggestedHighlights(arg1:number):Promise<void>;

export function CreateAssetMiddleware():Promise<assetserver.Middleware>;

export function CreateProject(arg1:string,arg2:string):Promise<services.ProjectResponse>;

export function CreateVideoClip(arg1:number,arg2:string):Promise<services.VideoClipResponse>;

export function DeleteHighlight(arg1:number,arg2:string):Promise<void>;

export function DeleteOpenAIApiKey():Promise<void>;

export function DeleteOpenRouterApiKey():Promise<void>;

export function DeleteProject(arg1:number):Promise<void>;

export function DeleteSetting(arg1:string):Promise<void>;

export function DeleteVideoClip(arg1:number):Promise<void>;

export function ExportIndividualHighlights(arg1:number,arg2:string):Promise<string>;

export function ExportStitchedHighlights(arg1:number,arg2:string):Promise<string>;

export function GetContext():Promise<context.Context>;

export function GetExportProgress(arg1:string):Promise<Record<string, any>>;

export function GetOpenAIApiKey():Promise<string>;

export function GetOpenRouterApiKey():Promise<string>;

export function GetProjectAISettings(arg1:number):Promise<Record<string, string>>;

export function GetProjectAISuggestion(arg1:number):Promise<Record<string, any>>;

export function GetProjectByID(arg1:number):Promise<services.ProjectResponse>;

export function GetProjectExportJobs(arg1:number):Promise<Array<any>>;

export function GetProjectHighlightAISettings(arg1:number):Promise<Record<string, string>>;

export function GetProjectHighlightOrder(arg1:number):Promise<Array<string>>;

export function GetProjectHighlights(arg1:number):Promise<Array<any>>;

export function GetProjectService():Promise<services.ProjectService>;

export function GetProjects():Promise<Array<services.ProjectResponse>>;

export function GetRepository():Promise<db.Repository>;

export function GetSetting(arg1:string):Promise<string>;

export function GetSettingsService():Promise<services.SettingsService>;

export function GetSuggestedHighlights(arg1:number):Promise<Array<any>>;

export function GetThemePreference():Promise<string>;

export function GetVideoClipService():Promise<services.VideoClipService>;

export function GetVideoClipsByProject(arg1:number):Promise<Array<services.VideoClipResponse>>;

export function GetVideoFileInfo(arg1:string):Promise<services.LocalVideoFile>;

export function GetVideoURL(arg1:string):Promise<string>;

export function OnFileDrop(arg1:context.Context,arg2:number,arg3:number,arg4:Array<string>):Promise<void>;

export function ReorderHighlightsWithAI(arg1:number,arg2:string,arg3:string):Promise<Array<string>>;

export function SaveOpenAIApiKey(arg1:string):Promise<void>;

export function SaveOpenRouterApiKey(arg1:string):Promise<void>;

export function SaveProjectAISettings(arg1:number,arg2:Record<string, string>):Promise<void>;

export function SaveProjectHighlightAISettings(arg1:number,arg2:Record<string, string>):Promise<void>;

export function SaveSetting(arg1:string,arg2:string):Promise<void>;

export function SaveThemePreference(arg1:string):Promise<void>;

export function SelectExportFolder():Promise<string>;

export function SelectVideoFiles():Promise<Array<services.LocalVideoFile>>;

export function SuggestHighlightsWithAI(arg1:number,arg2:string,arg3:string):Promise<Array<any>>;

export function TestOpenAIApiKey():Promise<Record<string, any>>;

export function TestOpenRouterApiKey():Promise<Record<string, any>>;

export function TranscribeVideoClip(arg1:number):Promise<app.TranscriptionResponse>;

export function UpdateProject(arg1:number,arg2:string,arg3:string):Promise<services.ProjectResponse>;

export function UpdateProjectHighlightOrder(arg1:number,arg2:Array<string>):Promise<void>;

export function UpdateVideoClip(arg1:number,arg2:string,arg3:string):Promise<services.VideoClipResponse>;

export function UpdateVideoClipHighlights(arg1:number,arg2:Array<any>):Promise<void>;

export function UpdateVideoClipSuggestedHighlights(arg1:number,arg2:Array<any>):Promise<void>;
