// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelExport(arg1) {
  return window['go']['app']['App']['CancelExport'](arg1);
}

export function ClearSuggestedHighlights(arg1) {
  return window['go']['app']['App']['ClearSuggestedHighlights'](arg1);
}

export function CreateAssetMiddleware() {
  return window['go']['app']['App']['CreateAssetMiddleware']();
}

export function CreateProject(arg1, arg2) {
  return window['go']['app']['App']['CreateProject'](arg1, arg2);
}

export function CreateVideoClip(arg1, arg2) {
  return window['go']['app']['App']['CreateVideoClip'](arg1, arg2);
}

export function DeleteHighlight(arg1, arg2) {
  return window['go']['app']['App']['DeleteHighlight'](arg1, arg2);
}

export function DeleteOpenAIApiKey() {
  return window['go']['app']['App']['DeleteOpenAIApiKey']();
}

export function DeleteOpenRouterApiKey() {
  return window['go']['app']['App']['DeleteOpenRouterApiKey']();
}

export function DeleteProject(arg1) {
  return window['go']['app']['App']['DeleteProject'](arg1);
}

export function DeleteSetting(arg1) {
  return window['go']['app']['App']['DeleteSetting'](arg1);
}

export function DeleteVideoClip(arg1) {
  return window['go']['app']['App']['DeleteVideoClip'](arg1);
}

export function ExportIndividualHighlights(arg1, arg2) {
  return window['go']['app']['App']['ExportIndividualHighlights'](arg1, arg2);
}

export function ExportStitchedHighlights(arg1, arg2) {
  return window['go']['app']['App']['ExportStitchedHighlights'](arg1, arg2);
}

export function GetContext() {
  return window['go']['app']['App']['GetContext']();
}

export function GetExportProgress(arg1) {
  return window['go']['app']['App']['GetExportProgress'](arg1);
}

export function GetOpenAIApiKey() {
  return window['go']['app']['App']['GetOpenAIApiKey']();
}

export function GetOpenRouterApiKey() {
  return window['go']['app']['App']['GetOpenRouterApiKey']();
}

export function GetProjectAISettings(arg1) {
  return window['go']['app']['App']['GetProjectAISettings'](arg1);
}

export function GetProjectAISuggestion(arg1) {
  return window['go']['app']['App']['GetProjectAISuggestion'](arg1);
}

export function GetProjectByID(arg1) {
  return window['go']['app']['App']['GetProjectByID'](arg1);
}

export function GetProjectExportJobs(arg1) {
  return window['go']['app']['App']['GetProjectExportJobs'](arg1);
}

export function GetProjectHighlightAISettings(arg1) {
  return window['go']['app']['App']['GetProjectHighlightAISettings'](arg1);
}

export function GetProjectHighlightOrder(arg1) {
  return window['go']['app']['App']['GetProjectHighlightOrder'](arg1);
}

export function GetProjectHighlights(arg1) {
  return window['go']['app']['App']['GetProjectHighlights'](arg1);
}

export function GetProjectService() {
  return window['go']['app']['App']['GetProjectService']();
}

export function GetProjects() {
  return window['go']['app']['App']['GetProjects']();
}

export function GetRepository() {
  return window['go']['app']['App']['GetRepository']();
}

export function GetSetting(arg1) {
  return window['go']['app']['App']['GetSetting'](arg1);
}

export function GetSettingsService() {
  return window['go']['app']['App']['GetSettingsService']();
}

export function GetSuggestedHighlights(arg1) {
  return window['go']['app']['App']['GetSuggestedHighlights'](arg1);
}

export function GetThemePreference() {
  return window['go']['app']['App']['GetThemePreference']();
}

export function GetVideoClipService() {
  return window['go']['app']['App']['GetVideoClipService']();
}

export function GetVideoClipsByProject(arg1) {
  return window['go']['app']['App']['GetVideoClipsByProject'](arg1);
}

export function GetVideoFileInfo(arg1) {
  return window['go']['app']['App']['GetVideoFileInfo'](arg1);
}

export function GetVideoURL(arg1) {
  return window['go']['app']['App']['GetVideoURL'](arg1);
}

export function OnFileDrop(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['OnFileDrop'](arg1, arg2, arg3, arg4);
}

export function ReorderHighlightsWithAI(arg1, arg2, arg3) {
  return window['go']['app']['App']['ReorderHighlightsWithAI'](arg1, arg2, arg3);
}

export function SaveOpenAIApiKey(arg1) {
  return window['go']['app']['App']['SaveOpenAIApiKey'](arg1);
}

export function SaveOpenRouterApiKey(arg1) {
  return window['go']['app']['App']['SaveOpenRouterApiKey'](arg1);
}

export function SaveProjectAISettings(arg1, arg2) {
  return window['go']['app']['App']['SaveProjectAISettings'](arg1, arg2);
}

export function SaveProjectHighlightAISettings(arg1, arg2) {
  return window['go']['app']['App']['SaveProjectHighlightAISettings'](arg1, arg2);
}

export function SaveSetting(arg1, arg2) {
  return window['go']['app']['App']['SaveSetting'](arg1, arg2);
}

export function SaveThemePreference(arg1) {
  return window['go']['app']['App']['SaveThemePreference'](arg1);
}

export function SelectExportFolder() {
  return window['go']['app']['App']['SelectExportFolder']();
}

export function SelectVideoFiles() {
  return window['go']['app']['App']['SelectVideoFiles']();
}

export function SuggestHighlightsWithAI(arg1, arg2, arg3) {
  return window['go']['app']['App']['SuggestHighlightsWithAI'](arg1, arg2, arg3);
}

export function TestOpenAIApiKey() {
  return window['go']['app']['App']['TestOpenAIApiKey']();
}

export function TestOpenRouterApiKey() {
  return window['go']['app']['App']['TestOpenRouterApiKey']();
}

export function TranscribeVideoClip(arg1) {
  return window['go']['app']['App']['TranscribeVideoClip'](arg1);
}

export function UpdateProject(arg1, arg2, arg3) {
  return window['go']['app']['App']['UpdateProject'](arg1, arg2, arg3);
}

export function UpdateProjectHighlightOrder(arg1, arg2) {
  return window['go']['app']['App']['UpdateProjectHighlightOrder'](arg1, arg2);
}

export function UpdateVideoClip(arg1, arg2, arg3) {
  return window['go']['app']['App']['UpdateVideoClip'](arg1, arg2, arg3);
}

export function UpdateVideoClipHighlights(arg1, arg2) {
  return window['go']['app']['App']['UpdateVideoClipHighlights'](arg1, arg2);
}

export function UpdateVideoClipSuggestedHighlights(arg1, arg2) {
  return window['go']['app']['App']['UpdateVideoClipSuggestedHighlights'](arg1, arg2);
}
