// Code generated by ent, DO NOT EDIT.

package project

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the project type in the database.
	Label = "project"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldDescription holds the string denoting the description field in the database.
	FieldDescription = "description"
	// FieldPath holds the string denoting the path field in the database.
	FieldPath = "path"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldAiModel holds the string denoting the ai_model field in the database.
	FieldAiModel = "ai_model"
	// FieldAiPrompt holds the string denoting the ai_prompt field in the database.
	FieldAiPrompt = "ai_prompt"
	// FieldAiSuggestionOrder holds the string denoting the ai_suggestion_order field in the database.
	FieldAiSuggestionOrder = "ai_suggestion_order"
	// FieldAiSuggestionModel holds the string denoting the ai_suggestion_model field in the database.
	FieldAiSuggestionModel = "ai_suggestion_model"
	// FieldAiSuggestionCreatedAt holds the string denoting the ai_suggestion_created_at field in the database.
	FieldAiSuggestionCreatedAt = "ai_suggestion_created_at"
	// FieldAiHighlightModel holds the string denoting the ai_highlight_model field in the database.
	FieldAiHighlightModel = "ai_highlight_model"
	// FieldAiHighlightPrompt holds the string denoting the ai_highlight_prompt field in the database.
	FieldAiHighlightPrompt = "ai_highlight_prompt"
	// FieldActiveTab holds the string denoting the active_tab field in the database.
	FieldActiveTab = "active_tab"
	// FieldAiSilenceImprovements holds the string denoting the ai_silence_improvements field in the database.
	FieldAiSilenceImprovements = "ai_silence_improvements"
	// FieldAiSilenceModel holds the string denoting the ai_silence_model field in the database.
	FieldAiSilenceModel = "ai_silence_model"
	// FieldAiSilenceCreatedAt holds the string denoting the ai_silence_created_at field in the database.
	FieldAiSilenceCreatedAt = "ai_silence_created_at"
	// FieldHighlightOrder holds the string denoting the highlight_order field in the database.
	FieldHighlightOrder = "highlight_order"
	// FieldOrderHistory holds the string denoting the order_history field in the database.
	FieldOrderHistory = "order_history"
	// FieldOrderHistoryIndex holds the string denoting the order_history_index field in the database.
	FieldOrderHistoryIndex = "order_history_index"
	// EdgeVideoClips holds the string denoting the video_clips edge name in mutations.
	EdgeVideoClips = "video_clips"
	// EdgeExportJobs holds the string denoting the export_jobs edge name in mutations.
	EdgeExportJobs = "export_jobs"
	// Table holds the table name of the project in the database.
	Table = "projects"
	// VideoClipsTable is the table that holds the video_clips relation/edge.
	VideoClipsTable = "video_clips"
	// VideoClipsInverseTable is the table name for the VideoClip entity.
	// It exists in this package in order to avoid circular dependency with the "videoclip" package.
	VideoClipsInverseTable = "video_clips"
	// VideoClipsColumn is the table column denoting the video_clips relation/edge.
	VideoClipsColumn = "project_video_clips"
	// ExportJobsTable is the table that holds the export_jobs relation/edge.
	ExportJobsTable = "export_jobs"
	// ExportJobsInverseTable is the table name for the ExportJob entity.
	// It exists in this package in order to avoid circular dependency with the "exportjob" package.
	ExportJobsInverseTable = "export_jobs"
	// ExportJobsColumn is the table column denoting the export_jobs relation/edge.
	ExportJobsColumn = "project_export_jobs"
)

// Columns holds all SQL columns for project fields.
var Columns = []string{
	FieldID,
	FieldName,
	FieldDescription,
	FieldPath,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldAiModel,
	FieldAiPrompt,
	FieldAiSuggestionOrder,
	FieldAiSuggestionModel,
	FieldAiSuggestionCreatedAt,
	FieldAiHighlightModel,
	FieldAiHighlightPrompt,
	FieldActiveTab,
	FieldAiSilenceImprovements,
	FieldAiSilenceModel,
	FieldAiSilenceCreatedAt,
	FieldHighlightOrder,
	FieldOrderHistory,
	FieldOrderHistoryIndex,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
	// PathValidator is a validator for the "path" field. It is called by the builders before save.
	PathValidator func(string) error
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// DefaultAiModel holds the default value on creation for the "ai_model" field.
	DefaultAiModel string
	// DefaultAiHighlightModel holds the default value on creation for the "ai_highlight_model" field.
	DefaultAiHighlightModel string
	// DefaultActiveTab holds the default value on creation for the "active_tab" field.
	DefaultActiveTab string
	// DefaultOrderHistoryIndex holds the default value on creation for the "order_history_index" field.
	DefaultOrderHistoryIndex int
)

// OrderOption defines the ordering options for the Project queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByDescription orders the results by the description field.
func ByDescription(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDescription, opts...).ToFunc()
}

// ByPath orders the results by the path field.
func ByPath(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPath, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByAiModel orders the results by the ai_model field.
func ByAiModel(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAiModel, opts...).ToFunc()
}

// ByAiPrompt orders the results by the ai_prompt field.
func ByAiPrompt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAiPrompt, opts...).ToFunc()
}

// ByAiSuggestionModel orders the results by the ai_suggestion_model field.
func ByAiSuggestionModel(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAiSuggestionModel, opts...).ToFunc()
}

// ByAiSuggestionCreatedAt orders the results by the ai_suggestion_created_at field.
func ByAiSuggestionCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAiSuggestionCreatedAt, opts...).ToFunc()
}

// ByAiHighlightModel orders the results by the ai_highlight_model field.
func ByAiHighlightModel(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAiHighlightModel, opts...).ToFunc()
}

// ByAiHighlightPrompt orders the results by the ai_highlight_prompt field.
func ByAiHighlightPrompt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAiHighlightPrompt, opts...).ToFunc()
}

// ByActiveTab orders the results by the active_tab field.
func ByActiveTab(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldActiveTab, opts...).ToFunc()
}

// ByAiSilenceModel orders the results by the ai_silence_model field.
func ByAiSilenceModel(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAiSilenceModel, opts...).ToFunc()
}

// ByAiSilenceCreatedAt orders the results by the ai_silence_created_at field.
func ByAiSilenceCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAiSilenceCreatedAt, opts...).ToFunc()
}

// ByOrderHistoryIndex orders the results by the order_history_index field.
func ByOrderHistoryIndex(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOrderHistoryIndex, opts...).ToFunc()
}

// ByVideoClipsCount orders the results by video_clips count.
func ByVideoClipsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newVideoClipsStep(), opts...)
	}
}

// ByVideoClips orders the results by video_clips terms.
func ByVideoClips(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newVideoClipsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByExportJobsCount orders the results by export_jobs count.
func ByExportJobsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newExportJobsStep(), opts...)
	}
}

// ByExportJobs orders the results by export_jobs terms.
func ByExportJobs(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newExportJobsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newVideoClipsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(VideoClipsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, VideoClipsTable, VideoClipsColumn),
	)
}
func newExportJobsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ExportJobsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, ExportJobsTable, ExportJobsColumn),
	)
}
