// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// ProjectsColumns holds the columns for the "projects" table.
	ProjectsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString},
		{Name: "description", Type: field.TypeString, Nullable: true, Size: 2147483647},
		{Name: "path", Type: field.TypeString},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// ProjectsTable holds the schema information for the "projects" table.
	ProjectsTable = &schema.Table{
		Name:       "projects",
		Columns:    ProjectsColumns,
		PrimaryKey: []*schema.Column{ProjectsColumns[0]},
	}
	// SettingsColumns holds the columns for the "settings" table.
	SettingsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "key", Type: field.TypeString, Unique: true},
		{Name: "value", Type: field.TypeString, Nullable: true, Size: 2147483647},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// SettingsTable holds the schema information for the "settings" table.
	SettingsTable = &schema.Table{
		Name:       "settings",
		Columns:    SettingsColumns,
		PrimaryKey: []*schema.Column{SettingsColumns[0]},
	}
	// VideoClipsColumns holds the columns for the "video_clips" table.
	VideoClipsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString},
		{Name: "description", Type: field.TypeString, Nullable: true, Size: 2147483647},
		{Name: "file_path", Type: field.TypeString},
		{Name: "duration", Type: field.TypeFloat64, Nullable: true},
		{Name: "format", Type: field.TypeString, Nullable: true},
		{Name: "width", Type: field.TypeInt, Nullable: true},
		{Name: "height", Type: field.TypeInt, Nullable: true},
		{Name: "file_size", Type: field.TypeInt64, Nullable: true},
		{Name: "transcription", Type: field.TypeString, Nullable: true, Size: 2147483647},
		{Name: "transcription_words", Type: field.TypeJSON, Nullable: true},
		{Name: "transcription_language", Type: field.TypeString, Nullable: true},
		{Name: "transcription_duration", Type: field.TypeFloat64, Nullable: true},
		{Name: "highlights", Type: field.TypeJSON, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "project_video_clips", Type: field.TypeInt, Nullable: true},
	}
	// VideoClipsTable holds the schema information for the "video_clips" table.
	VideoClipsTable = &schema.Table{
		Name:       "video_clips",
		Columns:    VideoClipsColumns,
		PrimaryKey: []*schema.Column{VideoClipsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "video_clips_projects_video_clips",
				Columns:    []*schema.Column{VideoClipsColumns[16]},
				RefColumns: []*schema.Column{ProjectsColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		ProjectsTable,
		SettingsTable,
		VideoClipsTable,
	}
)

func init() {
	VideoClipsTable.ForeignKeys[0].RefTable = ProjectsTable
}
