// Code generated by ent, DO NOT EDIT.

package ent

import (
	"MYAPP/ent/exportjob"
	"MYAPP/ent/predicate"
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ExportJobDelete is the builder for deleting a ExportJob entity.
type ExportJobDelete struct {
	config
	hooks    []Hook
	mutation *ExportJobMutation
}

// Where appends a list predicates to the ExportJobDelete builder.
func (ejd *ExportJobDelete) Where(ps ...predicate.ExportJob) *ExportJobDelete {
	ejd.mutation.Where(ps...)
	return ejd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (ejd *ExportJobDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, ejd.sqlExec, ejd.mutation, ejd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (ejd *ExportJobDelete) ExecX(ctx context.Context) int {
	n, err := ejd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (ejd *ExportJobDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(exportjob.Table, sqlgraph.NewFieldSpec(exportjob.FieldID, field.TypeInt))
	if ps := ejd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, ejd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	ejd.mutation.done = true
	return affected, err
}

// ExportJobDeleteOne is the builder for deleting a single ExportJob entity.
type ExportJobDeleteOne struct {
	ejd *ExportJobDelete
}

// Where appends a list predicates to the ExportJobDelete builder.
func (ejdo *ExportJobDeleteOne) Where(ps ...predicate.ExportJob) *ExportJobDeleteOne {
	ejdo.ejd.mutation.Where(ps...)
	return ejdo
}

// Exec executes the deletion query.
func (ejdo *ExportJobDeleteOne) Exec(ctx context.Context) error {
	n, err := ejdo.ejd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{exportjob.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (ejdo *ExportJobDeleteOne) ExecX(ctx context.Context) {
	if err := ejdo.Exec(ctx); err != nil {
		panic(err)
	}
}
