// Code generated by ent, DO NOT EDIT.

package ent

import (
	"MYAPP/ent/exportjob"
	"MYAPP/ent/project"
	"MYAPP/ent/schema"
	"MYAPP/ent/settings"
	"MYAPP/ent/videoclip"
	"time"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	exportjobFields := schema.ExportJob{}.Fields()
	_ = exportjobFields
	// exportjobDescJobID is the schema descriptor for job_id field.
	exportjobDescJobID := exportjobFields[0].Descriptor()
	// exportjob.JobIDValidator is a validator for the "job_id" field. It is called by the builders before save.
	exportjob.JobIDValidator = exportjobDescJobID.Validators[0].(func(string) error)
	// exportjobDescExportType is the schema descriptor for export_type field.
	exportjobDescExportType := exportjobFields[1].Descriptor()
	// exportjob.ExportTypeValidator is a validator for the "export_type" field. It is called by the builders before save.
	exportjob.ExportTypeValidator = exportjobDescExportType.Validators[0].(func(string) error)
	// exportjobDescOutputPath is the schema descriptor for output_path field.
	exportjobDescOutputPath := exportjobFields[2].Descriptor()
	// exportjob.OutputPathValidator is a validator for the "output_path" field. It is called by the builders before save.
	exportjob.OutputPathValidator = exportjobDescOutputPath.Validators[0].(func(string) error)
	// exportjobDescStage is the schema descriptor for stage field.
	exportjobDescStage := exportjobFields[3].Descriptor()
	// exportjob.DefaultStage holds the default value on creation for the stage field.
	exportjob.DefaultStage = exportjobDescStage.Default.(string)
	// exportjobDescProgress is the schema descriptor for progress field.
	exportjobDescProgress := exportjobFields[4].Descriptor()
	// exportjob.DefaultProgress holds the default value on creation for the progress field.
	exportjob.DefaultProgress = exportjobDescProgress.Default.(float64)
	// exportjobDescTotalFiles is the schema descriptor for total_files field.
	exportjobDescTotalFiles := exportjobFields[6].Descriptor()
	// exportjob.DefaultTotalFiles holds the default value on creation for the total_files field.
	exportjob.DefaultTotalFiles = exportjobDescTotalFiles.Default.(int)
	// exportjobDescProcessedFiles is the schema descriptor for processed_files field.
	exportjobDescProcessedFiles := exportjobFields[7].Descriptor()
	// exportjob.DefaultProcessedFiles holds the default value on creation for the processed_files field.
	exportjob.DefaultProcessedFiles = exportjobDescProcessedFiles.Default.(int)
	// exportjobDescIsComplete is the schema descriptor for is_complete field.
	exportjobDescIsComplete := exportjobFields[8].Descriptor()
	// exportjob.DefaultIsComplete holds the default value on creation for the is_complete field.
	exportjob.DefaultIsComplete = exportjobDescIsComplete.Default.(bool)
	// exportjobDescHasError is the schema descriptor for has_error field.
	exportjobDescHasError := exportjobFields[9].Descriptor()
	// exportjob.DefaultHasError holds the default value on creation for the has_error field.
	exportjob.DefaultHasError = exportjobDescHasError.Default.(bool)
	// exportjobDescIsCancelled is the schema descriptor for is_cancelled field.
	exportjobDescIsCancelled := exportjobFields[11].Descriptor()
	// exportjob.DefaultIsCancelled holds the default value on creation for the is_cancelled field.
	exportjob.DefaultIsCancelled = exportjobDescIsCancelled.Default.(bool)
	// exportjobDescCreatedAt is the schema descriptor for created_at field.
	exportjobDescCreatedAt := exportjobFields[12].Descriptor()
	// exportjob.DefaultCreatedAt holds the default value on creation for the created_at field.
	exportjob.DefaultCreatedAt = exportjobDescCreatedAt.Default.(func() time.Time)
	// exportjobDescUpdatedAt is the schema descriptor for updated_at field.
	exportjobDescUpdatedAt := exportjobFields[13].Descriptor()
	// exportjob.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	exportjob.DefaultUpdatedAt = exportjobDescUpdatedAt.Default.(func() time.Time)
	// exportjob.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	exportjob.UpdateDefaultUpdatedAt = exportjobDescUpdatedAt.UpdateDefault.(func() time.Time)
	projectFields := schema.Project{}.Fields()
	_ = projectFields
	// projectDescName is the schema descriptor for name field.
	projectDescName := projectFields[0].Descriptor()
	// project.NameValidator is a validator for the "name" field. It is called by the builders before save.
	project.NameValidator = projectDescName.Validators[0].(func(string) error)
	// projectDescPath is the schema descriptor for path field.
	projectDescPath := projectFields[2].Descriptor()
	// project.PathValidator is a validator for the "path" field. It is called by the builders before save.
	project.PathValidator = projectDescPath.Validators[0].(func(string) error)
	// projectDescCreatedAt is the schema descriptor for created_at field.
	projectDescCreatedAt := projectFields[3].Descriptor()
	// project.DefaultCreatedAt holds the default value on creation for the created_at field.
	project.DefaultCreatedAt = projectDescCreatedAt.Default.(func() time.Time)
	// projectDescUpdatedAt is the schema descriptor for updated_at field.
	projectDescUpdatedAt := projectFields[4].Descriptor()
	// project.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	project.DefaultUpdatedAt = projectDescUpdatedAt.Default.(func() time.Time)
	// project.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	project.UpdateDefaultUpdatedAt = projectDescUpdatedAt.UpdateDefault.(func() time.Time)
	// projectDescAiModel is the schema descriptor for ai_model field.
	projectDescAiModel := projectFields[5].Descriptor()
	// project.DefaultAiModel holds the default value on creation for the ai_model field.
	project.DefaultAiModel = projectDescAiModel.Default.(string)
	// projectDescAiHighlightModel is the schema descriptor for ai_highlight_model field.
	projectDescAiHighlightModel := projectFields[10].Descriptor()
	// project.DefaultAiHighlightModel holds the default value on creation for the ai_highlight_model field.
	project.DefaultAiHighlightModel = projectDescAiHighlightModel.Default.(string)
	// projectDescActiveTab is the schema descriptor for active_tab field.
	projectDescActiveTab := projectFields[12].Descriptor()
	// project.DefaultActiveTab holds the default value on creation for the active_tab field.
	project.DefaultActiveTab = projectDescActiveTab.Default.(string)
	// projectDescOrderHistoryIndex is the schema descriptor for order_history_index field.
	projectDescOrderHistoryIndex := projectFields[17].Descriptor()
	// project.DefaultOrderHistoryIndex holds the default value on creation for the order_history_index field.
	project.DefaultOrderHistoryIndex = projectDescOrderHistoryIndex.Default.(int)
	settingsFields := schema.Settings{}.Fields()
	_ = settingsFields
	// settingsDescKey is the schema descriptor for key field.
	settingsDescKey := settingsFields[0].Descriptor()
	// settings.KeyValidator is a validator for the "key" field. It is called by the builders before save.
	settings.KeyValidator = settingsDescKey.Validators[0].(func(string) error)
	// settingsDescCreatedAt is the schema descriptor for created_at field.
	settingsDescCreatedAt := settingsFields[2].Descriptor()
	// settings.DefaultCreatedAt holds the default value on creation for the created_at field.
	settings.DefaultCreatedAt = settingsDescCreatedAt.Default.(func() time.Time)
	// settingsDescUpdatedAt is the schema descriptor for updated_at field.
	settingsDescUpdatedAt := settingsFields[3].Descriptor()
	// settings.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	settings.DefaultUpdatedAt = settingsDescUpdatedAt.Default.(func() time.Time)
	// settings.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	settings.UpdateDefaultUpdatedAt = settingsDescUpdatedAt.UpdateDefault.(func() time.Time)
	videoclipFields := schema.VideoClip{}.Fields()
	_ = videoclipFields
	// videoclipDescName is the schema descriptor for name field.
	videoclipDescName := videoclipFields[0].Descriptor()
	// videoclip.NameValidator is a validator for the "name" field. It is called by the builders before save.
	videoclip.NameValidator = videoclipDescName.Validators[0].(func(string) error)
	// videoclipDescFilePath is the schema descriptor for file_path field.
	videoclipDescFilePath := videoclipFields[2].Descriptor()
	// videoclip.FilePathValidator is a validator for the "file_path" field. It is called by the builders before save.
	videoclip.FilePathValidator = videoclipDescFilePath.Validators[0].(func(string) error)
	// videoclipDescCreatedAt is the schema descriptor for created_at field.
	videoclipDescCreatedAt := videoclipFields[14].Descriptor()
	// videoclip.DefaultCreatedAt holds the default value on creation for the created_at field.
	videoclip.DefaultCreatedAt = videoclipDescCreatedAt.Default.(func() time.Time)
	// videoclipDescUpdatedAt is the schema descriptor for updated_at field.
	videoclipDescUpdatedAt := videoclipFields[15].Descriptor()
	// videoclip.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	videoclip.DefaultUpdatedAt = videoclipDescUpdatedAt.Default.(func() time.Time)
	// videoclip.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	videoclip.UpdateDefaultUpdatedAt = videoclipDescUpdatedAt.UpdateDefault.(func() time.Time)
	// videoclipDescHighlightsHistoryIndex is the schema descriptor for highlights_history_index field.
	videoclipDescHighlightsHistoryIndex := videoclipFields[17].Descriptor()
	// videoclip.DefaultHighlightsHistoryIndex holds the default value on creation for the highlights_history_index field.
	videoclip.DefaultHighlightsHistoryIndex = videoclipDescHighlightsHistoryIndex.Default.(int)
	// videoclipDescTranscriptionState is the schema descriptor for transcription_state field.
	videoclipDescTranscriptionState := videoclipFields[18].Descriptor()
	// videoclip.DefaultTranscriptionState holds the default value on creation for the transcription_state field.
	videoclip.DefaultTranscriptionState = videoclipDescTranscriptionState.Default.(string)
}
