// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Close() {
  return window['go']['main']['App']['Close']();
}

export function CreateProject(arg1, arg2) {
  return window['go']['main']['App']['CreateProject'](arg1, arg2);
}

export function CreateVideoClip(arg1, arg2) {
  return window['go']['main']['App']['CreateVideoClip'](arg1, arg2);
}

export function DeleteOpenAIApiKey() {
  return window['go']['main']['App']['DeleteOpenAIApiKey']();
}

export function DeleteProject(arg1) {
  return window['go']['main']['App']['DeleteProject'](arg1);
}

export function DeleteSetting(arg1) {
  return window['go']['main']['App']['DeleteSetting'](arg1);
}

export function DeleteVideoClip(arg1) {
  return window['go']['main']['App']['DeleteVideoClip'](arg1);
}

export function GetOpenAIApiKey() {
  return window['go']['main']['App']['GetOpenAIApiKey']();
}

export function GetProjectByID(arg1) {
  return window['go']['main']['App']['GetProjectByID'](arg1);
}

export function GetProjects() {
  return window['go']['main']['App']['GetProjects']();
}

export function GetSetting(arg1) {
  return window['go']['main']['App']['GetSetting'](arg1);
}

export function GetVideoClipsByProject(arg1) {
  return window['go']['main']['App']['GetVideoClipsByProject'](arg1);
}

export function GetVideoFileInfo(arg1) {
  return window['go']['main']['App']['GetVideoFileInfo'](arg1);
}

export function GetVideoURL(arg1) {
  return window['go']['main']['App']['GetVideoURL'](arg1);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function SaveOpenAIApiKey(arg1) {
  return window['go']['main']['App']['SaveOpenAIApiKey'](arg1);
}

export function SaveSetting(arg1, arg2) {
  return window['go']['main']['App']['SaveSetting'](arg1, arg2);
}

export function SelectVideoFiles() {
  return window['go']['main']['App']['SelectVideoFiles']();
}

export function TestOpenAIApiKey() {
  return window['go']['main']['App']['TestOpenAIApiKey']();
}

export function UpdateProject(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateProject'](arg1, arg2, arg3);
}

export function UpdateVideoClip(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateVideoClip'](arg1, arg2, arg3);
}
