// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CancelExport(arg1:string):Promise<void>;

export function ClearSuggestedHighlights(arg1:number):Promise<void>;

export function Close():Promise<void>;

export function CreateProject(arg1:string,arg2:string):Promise<main.ProjectResponse>;

export function CreateVideoClip(arg1:number,arg2:string):Promise<main.VideoClipResponse>;

export function DeleteHighlight(arg1:number,arg2:string):Promise<void>;

export function DeleteOpenAIApiKey():Promise<void>;

export function DeleteOpenRouterApiKey():Promise<void>;

export function DeleteProject(arg1:number):Promise<void>;

export function DeleteSetting(arg1:string):Promise<void>;

export function DeleteVideoClip(arg1:number):Promise<void>;

export function ExportIndividualHighlights(arg1:number,arg2:string):Promise<string>;

export function ExportStitchedHighlights(arg1:number,arg2:string):Promise<string>;

export function GetExportProgress(arg1:string):Promise<main.ExportProgress>;

export function GetOpenAIApiKey():Promise<string>;

export function GetOpenRouterApiKey():Promise<string>;

export function GetProjectAISettings(arg1:number):Promise<main.ProjectAISettings>;

export function GetProjectAISuggestion(arg1:number):Promise<main.ProjectAISuggestion>;

export function GetProjectByID(arg1:number):Promise<main.ProjectResponse>;

export function GetProjectExportJobs(arg1:number):Promise<Array<main.ExportProgress>>;

export function GetProjectHighlightAISettings(arg1:number):Promise<main.ProjectHighlightAISettings>;

export function GetProjectHighlightOrder(arg1:number):Promise<Array<string>>;

export function GetProjectHighlights(arg1:number):Promise<Array<main.ProjectHighlight>>;

export function GetProjects():Promise<Array<main.ProjectResponse>>;

export function GetSetting(arg1:string):Promise<string>;

export function GetSuggestedHighlights(arg1:number):Promise<Array<main.HighlightSuggestion>>;

export function GetThemePreference():Promise<string>;

export function GetVideoClipsByProject(arg1:number):Promise<Array<main.VideoClipResponse>>;

export function GetVideoFileInfo(arg1:string):Promise<main.LocalVideoFile>;

export function GetVideoURL(arg1:string):Promise<string>;

export function Greet(arg1:string):Promise<string>;

export function RecoverActiveExportJobs():Promise<void>;

export function ReorderHighlightsWithAI(arg1:number,arg2:string):Promise<Array<string>>;

export function SaveOpenAIApiKey(arg1:string):Promise<void>;

export function SaveOpenRouterApiKey(arg1:string):Promise<void>;

export function SaveProjectAISettings(arg1:number,arg2:main.ProjectAISettings):Promise<void>;

export function SaveProjectHighlightAISettings(arg1:number,arg2:main.ProjectHighlightAISettings):Promise<void>;

export function SaveSetting(arg1:string,arg2:string):Promise<void>;

export function SaveThemePreference(arg1:string):Promise<void>;

export function SelectExportFolder():Promise<string>;

export function SelectVideoFiles():Promise<Array<main.LocalVideoFile>>;

export function SuggestHighlightsWithAI(arg1:number,arg2:number,arg3:string):Promise<Array<main.HighlightSuggestion>>;

export function TestOpenAIApiKey():Promise<main.TestOpenAIApiKeyResponse>;

export function TestOpenRouterApiKey():Promise<main.TestOpenRouterApiKeyResponse>;

export function TranscribeVideoClip(arg1:number):Promise<main.TranscriptionResponse>;

export function UpdateProject(arg1:number,arg2:string,arg3:string):Promise<main.ProjectResponse>;

export function UpdateProjectHighlightOrder(arg1:number,arg2:Array<string>):Promise<void>;

export function UpdateVideoClip(arg1:number,arg2:string,arg3:string):Promise<main.VideoClipResponse>;

export function UpdateVideoClipHighlights(arg1:number,arg2:Array<main.Highlight>):Promise<void>;
