// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function Close():Promise<void>;

export function CreateProject(arg1:string,arg2:string):Promise<main.ProjectResponse>;

export function CreateVideoClip(arg1:number,arg2:string):Promise<main.VideoClipResponse>;

export function DeleteProject(arg1:number):Promise<void>;

export function DeleteVideoClip(arg1:number):Promise<void>;

export function GetProjectByID(arg1:number):Promise<main.ProjectResponse>;

export function GetProjects():Promise<Array<main.ProjectResponse>>;

export function GetVideoClipsByProject(arg1:number):Promise<Array<main.VideoClipResponse>>;

export function GetVideoFileInfo(arg1:string):Promise<main.LocalVideoFile>;

export function Greet(arg1:string):Promise<string>;

export function SelectVideoFiles():Promise<Array<main.LocalVideoFile>>;

export function UpdateProject(arg1:number,arg2:string,arg3:string):Promise<main.ProjectResponse>;

export function UpdateVideoClip(arg1:number,arg2:string,arg3:string):Promise<main.VideoClipResponse>;
