// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Close() {
  return window['go']['main']['App']['Close']();
}

export function CreateProject(arg1, arg2) {
  return window['go']['main']['App']['CreateProject'](arg1, arg2);
}

export function CreateVideoClip(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['CreateVideoClip'](arg1, arg2, arg3, arg4);
}

export function GetProjects() {
  return window['go']['main']['App']['GetProjects']();
}

export function GetVideoClipsByProject(arg1) {
  return window['go']['main']['App']['GetVideoClipsByProject'](arg1);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}
